name: Test Installation Process
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true

jobs:
  test-install-process:
    env:
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      BUILDKIT_INLINE_CACHE: 1
    runs-on: ubuntu-20.04
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v2

      - name: Configure
        run: |
          docker --version
          docker compose --version

      - name: Test
        run: |
          docker compose pull 
          docker compose up ac-db-import 
          docker compose up -d ac-client-data
          docker compose run --rm ac-authserver /bin/bash -c "timeout 5m ./env/dist/bin/authserver -dry-run"
          docker compose run --rm ac-worldserver /bin/bash -c "timeout 5m ./env/dist/bin/worldserver -dry-run"
